owner: vector-co-uz # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository
secrets:
  - NOTIFICATION_GOTIFY
  - NOTIFICATION_GOTIFY_URL
  - NOTIFICATION_GOTIFY_TOKEN
#  - NOTIFICATION_GOTIFY_TITLE
#  - NOTIFICATION_GOTIFY_PRIORITY

sites:
  - name: Homeassistant
    url: https://ha.vector.co.uz
  - name: Frigate
    url: https://frigate.vector.co.uz
  - name: Links
    url: https://links.vector.co.uz
  - name: Gotify
    url: https://gtfy.vector.co.uz
  - name: Jellyfin
    url: https://fin.vector.co.uz
    
    
#notifications:
#  - type: gotify
      
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
  
status-website:
  theme: night
  cname: uptime.vector.co.uz
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Uptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
